import React, { useEffect, useMemo, useState } from 'react';
import { Store, Product, Order } from '../../types';
import { api } from '../../lib/api';
import { Building2, Users, Package, ShoppingBag, CreditCard, ShieldCheck, Search, ExternalLink, LogOut, RefreshCw, Globe, TrendingUp, CheckCircle2, XCircle, Ban, PlayCircle, Edit3, Trash2, Save, X, Store as StoreIcon } from 'lucide-react';

interface AdminDashboardProps { stores: Store[]; onUpdateStore: (updatedStore: Store) => void; onNavigateHome: () => void; onLogoutAdmin: () => void; onOpenStorefront: (store: Store) => void; onOpenInfinityFreeModal: () => void; }

type Tab = 'overview'|'merchants'|'stores'|'products'|'orders'|'subscriptions';
const statuses = ['جديد','قيد المعالجة','تم الشحن','تم التوصيل','ملغي'];

export const AdminDashboard: React.FC<AdminDashboardProps> = ({ stores, onUpdateStore, onNavigateHome, onLogoutAdmin, onOpenStorefront, onOpenInfinityFreeModal }) => {
  const [tab,setTab]=useState<Tab>('overview'); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  const [stats,setStats]=useState<any>({}); const [merchants,setMerchants]=useState<any[]>([]); const [adminStores,setAdminStores]=useState<Store[]>(stores); const [orders,setOrders]=useState<any[]>([]); const [search,setSearch]=useState('');
  const [editingProduct,setEditingProduct]=useState<{storeId:string,product:Product}|null>(null);

  const load = async () => { setLoading(true); setError(''); try { const [d,m,s,o]=await Promise.all([api.dashboard(),api.merchants(),api.stores(),api.orders()]); if(!d.ok) throw new Error(d.error); if(!m.ok) throw new Error(m.error); if(!s.ok) throw new Error(s.error); if(!o.ok) throw new Error(o.error); setStats(d.data?.stats||{}); setMerchants(d.data?.merchants||m.data?.merchants||[]); setAdminStores(s.data?.stores||[]); setOrders(o.data?.orders||[]); } catch(e:any){setError(e.message||'تعذر تحميل بيانات الإدارة.');} finally{setLoading(false);} };
  useEffect(()=>{load();},[]);
  const products=useMemo(()=>adminStores.flatMap(s=>(s.products||[]).map(p=>({p,s}))),[adminStores]);
  const filteredMerchants=merchants.filter(m=>`${m.name} ${m.phone||''} ${m.email||''} ${m.company_name||''}`.toLowerCase().includes(search.toLowerCase()));
  const filteredStores=adminStores.filter(s=>`${s.name} ${s.merchantName} ${s.category} ${s.slug}`.toLowerCase().includes(search.toLowerCase()));
  const filteredProducts=products.filter(({p,s})=>`${p.title} ${p.sku} ${s.name}`.toLowerCase().includes(search.toLowerCase()));
  const filteredOrders=orders.filter(o=>`${o.id} ${o.store_name||''} ${o.merchant_name||''} ${o.order?.customerName||''} ${o.order?.customerPhone||''}`.toLowerCase().includes(search.toLowerCase()));

  const setMerchantStatus=async(id:string,status:'active'|'suspended')=>{setError('');const r=await api.merchantStatus(id,status);if(!r.ok){setError(r.error||'فشل تحديث البائع');return;}setMerchants(x=>x.map(m=>m.id===id?{...m,status}:m));};
  const setOrderStatus=async(id:string,status:string)=>{const r=await api.orderStatus(id,status);if(!r.ok){setError(r.error||'فشل تحديث الطلب');return;}setOrders(x=>x.map(o=>o.id===id?{...o,status,order:{...(o.order||{}),status}}:o));};
  const setSubscription=async(store:Store,status:'active_trial'|'subscribed'|'pending_baridimob'|'expired')=>{const sub={...(store.subscription||{}),planName:'خطة تجار الجملة - Youmi B2B Pro',status,monthlyFeeDzd:3500,isTrialActive:status==='active_trial',trialDaysLeft:status==='active_trial'?30:0};const r=await api.adminSubscription(store.id,sub);if(!r.ok){setError(r.error||'فشل تحديث الاشتراك');return;}const updated=r.data?.store as Store;if(updated){setAdminStores(x=>x.map(s=>s.id===updated.id?updated:s));onUpdateStore(updated);}};
  const saveProduct=async()=>{if(!editingProduct)return;const r=await api.adminSaveProduct(editingProduct.storeId,editingProduct.product);if(!r.ok){setError(r.error||'فشل حفظ المنتج');return;}if(r.data?.store){setAdminStores(x=>x.map(s=>s.id===r.data.store.id?r.data.store:s));onUpdateStore(r.data.store);}setEditingProduct(null);};
  const deleteProduct=async(storeId:string,productId:string)=>{if(!confirm('هل تريد حذف هذا المنتج؟'))return;const r=await api.adminDeleteProduct(storeId,productId);if(!r.ok){setError(r.error||'فشل حذف المنتج');return;}if(r.data?.store){setAdminStores(x=>x.map(s=>s.id===r.data.store.id?r.data.store:s));onUpdateStore(r.data.store);}};

  const nav=(id:Tab,label:string,icon:React.ReactNode)=><button onClick={()=>{setTab(id);setSearch('')}} className={`px-4 py-2.5 rounded-2xl text-xs font-bold flex items-center gap-2 border transition ${tab===id?'bg-slate-900 text-white border-slate-900':'bg-white text-slate-600 border-slate-200 hover:bg-slate-50'}`}>{icon}{label}</button>;
  return <div className="min-h-screen bg-[#F8FAFC] text-slate-800 font-['Tajawal'] dir-rtl">
    <header className="sticky top-0 z-40 bg-gradient-to-r from-slate-950 via-indigo-950 to-slate-950 text-white border-b border-indigo-900 shadow-md"><div className="max-w-[1500px] mx-auto px-4 lg:px-8 py-3 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-2xl bg-amber-400 text-slate-950 flex items-center justify-center"><ShieldCheck/></div><div><h1 className="font-black font-['Cairo']">لوحة إدارة Marketplace — Youmi</h1><p className="text-[11px] text-indigo-200">البائعون • المتاجر • المنتجات • الطلبات • الاشتراكات</p></div></div><div className="flex gap-2"><button onClick={load} className="px-3 py-2 rounded-xl bg-white/10 border border-white/20 text-xs font-bold flex gap-1.5 items-center"><RefreshCw className="w-4 h-4"/>تحديث</button><button onClick={onOpenInfinityFreeModal} className="px-3 py-2 rounded-xl bg-emerald-500/10 border border-emerald-500/30 text-emerald-200 text-xs font-bold flex gap-1.5 items-center"><Globe className="w-4 h-4"/>الاستضافة</button><button onClick={onNavigateHome} className="px-3 py-2 rounded-xl bg-white/10 border border-white/20 text-xs font-bold">الرئيسية</button><button onClick={onLogoutAdmin} className="px-3 py-2 rounded-xl bg-rose-600 text-xs font-bold flex gap-1.5 items-center"><LogOut className="w-4 h-4"/>خروج</button></div></div></header>
    <main className="max-w-[1500px] mx-auto px-4 lg:px-8 py-6 space-y-5">
      {error&&<div className="p-3 rounded-2xl bg-rose-50 border border-rose-200 text-rose-700 text-xs font-bold">{error}</div>}
      {loading&&<div className="text-xs font-bold text-indigo-600">جاري تحديث لوحة الإدارة من الخادم...</div>}
      <div className="flex gap-2 overflow-x-auto pb-1">{nav('overview','نظرة عامة',<TrendingUp className="w-4 h-4"/>)}{nav('merchants','البائعون',<Users className="w-4 h-4"/>)}{nav('stores','المتاجر',<Building2 className="w-4 h-4"/>)}{nav('products','المنتجات',<Package className="w-4 h-4"/>)}{nav('orders','الطلبات',<ShoppingBag className="w-4 h-4"/>)}{nav('subscriptions','الاشتراكات',<CreditCard className="w-4 h-4"/>)}</div>
      {tab!=='overview'&&<div className="relative"><Search className="absolute right-3 top-3 w-4 h-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث في بيانات القسم الحالي..." className="w-full pr-10 pl-4 py-3 rounded-2xl border border-slate-200 bg-white text-sm outline-none focus:border-indigo-500"/></div>}
      {tab==='overview'&&<><div className="grid grid-cols-2 lg:grid-cols-5 gap-4">{[['البائعون',stats.merchants,Users],['المتاجر',stats.stores,Building2],['المنتجات',stats.products,Package],['الطلبات',stats.orders,ShoppingBag],['المبيعات',`${Number(stats.sales||0).toLocaleString()} دج`,TrendingUp]].map(([l,v,I]:any)=><div className="bg-white border border-slate-200 rounded-3xl p-5" key={String(l)}><I className="w-5 h-5 text-indigo-600 mb-3"/><p className="text-xs text-slate-500 font-bold">{l}</p><p className="text-2xl font-black mt-1">{v||0}</p></div>)}</div><div className="grid lg:grid-cols-2 gap-5"><section className="bg-white rounded-3xl border border-slate-200 p-5"><h2 className="font-black mb-4">آخر البائعين</h2>{merchants.slice(0,6).map(m=><div className="flex justify-between py-3 border-b last:border-0" key={m.id}><div><b className="text-sm">{m.name}</b><p className="text-[11px] text-slate-500">{m.company_name||m.phone||'—'}</p></div><span className={`text-[10px] font-bold px-2 py-1 rounded-lg ${m.status==='suspended'?'bg-rose-50 text-rose-700':'bg-emerald-50 text-emerald-700'}`}>{m.status==='suspended'?'موقوف':'نشط'}</span></div>)}</section><section className="bg-white rounded-3xl border border-slate-200 p-5"><h2 className="font-black mb-4">آخر الطلبات</h2>{orders.slice(0,6).map(o=><div className="flex justify-between py-3 border-b last:border-0" key={o.id}><div><b className="font-mono text-xs">#{o.id}</b><p className="text-[11px] text-slate-500">{o.store_name||'—'} • {o.order?.customerName||'—'}</p></div><b className="text-emerald-700 text-xs">{Number(o.total_amount||o.order?.totalAmount||0).toLocaleString()} دج</b></div>)}</section></div></>}
      {tab==='merchants'&&<section className="bg-white rounded-3xl border border-slate-200 overflow-hidden"><div className="p-5 border-b"><h2 className="font-black">إدارة البائعين</h2><p className="text-xs text-slate-500 mt-1">تفعيل أو إيقاف حسابات البائعين. لا يوجد هنا نظام عمولات أو سحوبات.</p></div><div className="overflow-x-auto"><table className="w-full text-right text-xs"><thead className="bg-slate-50"><tr><th className="p-4">البائع</th><th className="p-4">الشركة</th><th className="p-4">التواصل</th><th className="p-4">الحالة</th><th className="p-4">الإجراء</th></tr></thead><tbody className="divide-y">{filteredMerchants.map(m=><tr key={m.id}><td className="p-4 font-bold">{m.name}</td><td className="p-4">{m.company_name||'—'}</td><td className="p-4">{m.phone||m.email||'—'}</td><td className="p-4"><span className={`px-2 py-1 rounded-lg font-bold ${m.status==='suspended'?'bg-rose-50 text-rose-700':'bg-emerald-50 text-emerald-700'}`}>{m.status==='suspended'?'موقوف':'نشط'}</span></td><td className="p-4"><button onClick={()=>setMerchantStatus(m.id,m.status==='suspended'?'active':'suspended')} className={`px-3 py-2 rounded-xl font-bold flex items-center gap-1 ${m.status==='suspended'?'bg-emerald-600 text-white':'bg-rose-50 text-rose-700 border border-rose-200'}`}>{m.status==='suspended'?<PlayCircle className="w-4 h-4"/>:<Ban className="w-4 h-4"/>}{m.status==='suspended'?'تفعيل':'إيقاف'}</button></td></tr>)}</tbody></table></div></section>}
      {tab==='stores'&&<section className="bg-white rounded-3xl border border-slate-200 overflow-hidden"><div className="p-5 border-b"><h2 className="font-black">إدارة المتاجر الفرعية</h2></div><div className="overflow-x-auto"><table className="w-full text-right text-xs"><thead className="bg-slate-50"><tr><th className="p-4">المتجر</th><th className="p-4">البائع</th><th className="p-4">التصنيف</th><th className="p-4">المنتجات</th><th className="p-4">الاشتراك</th><th className="p-4">فتح</th></tr></thead><tbody className="divide-y">{filteredStores.map(s=><tr key={s.id}><td className="p-4"><b>{s.name}</b><p className="font-mono text-[10px] text-slate-500">/{s.slug}</p></td><td className="p-4">{s.merchantName}</td><td className="p-4">{s.category}</td><td className="p-4 font-bold">{s.products?.length||0}</td><td className="p-4"><span className="px-2 py-1 rounded-lg bg-indigo-50 text-indigo-700 font-bold">{s.subscription?.status||'—'}</span></td><td className="p-4"><button onClick={()=>onOpenStorefront(s)} className="p-2 rounded-xl bg-slate-100"><ExternalLink className="w-4 h-4"/></button></td></tr>)}</tbody></table></div></section>}
      {tab==='products'&&<section className="bg-white rounded-3xl border border-slate-200 overflow-hidden"><div className="p-5 border-b"><h2 className="font-black">إدارة جميع المنتجات</h2></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 p-5">{filteredProducts.map(({p,s})=><div className="border border-slate-200 rounded-2xl p-3" key={`${s.id}-${p.id}`}><img src={p.images?.[0]} className="w-full aspect-square object-cover rounded-xl bg-slate-50"/><p className="text-[10px] text-indigo-600 font-bold mt-2">{s.name}</p><b className="text-sm line-clamp-1">{p.title}</b><p className="font-mono font-black text-emerald-700">{Number(p.price).toLocaleString()} دج</p><p className="text-[10px] text-slate-500">المخزون: {p.stock} • SKU: {p.sku}</p><div className="flex gap-2 mt-3"><button onClick={()=>setEditingProduct({storeId:s.id,product:{...p}})} className="flex-1 py-2 rounded-xl bg-indigo-50 text-indigo-700 font-bold flex justify-center gap-1"><Edit3 className="w-4 h-4"/>تعديل</button><button onClick={()=>deleteProduct(s.id,p.id)} className="p-2 rounded-xl bg-rose-50 text-rose-700"><Trash2 className="w-4 h-4"/></button></div></div>)}</div></section>}
      {tab==='orders'&&<section className="bg-white rounded-3xl border border-slate-200 overflow-hidden"><div className="p-5 border-b"><h2 className="font-black">إدارة الطلبات والشحن</h2></div><div className="overflow-x-auto"><table className="w-full text-right text-xs"><thead className="bg-slate-50"><tr><th className="p-4">الطلب</th><th className="p-4">المتجر / البائع</th><th className="p-4">العميل</th><th className="p-4">القيمة</th><th className="p-4">الحالة</th></tr></thead><tbody className="divide-y">{filteredOrders.map(o=><tr key={o.id}><td className="p-4 font-mono font-bold">#{o.id}</td><td className="p-4">{o.store_name}<br/><span className="text-[10px] text-slate-500">{o.merchant_name}</span></td><td className="p-4">{o.order?.customerName}<br/><span className="text-[10px]">{o.order?.customerPhone}</span></td><td className="p-4 font-black text-emerald-700">{Number(o.total_amount||o.order?.totalAmount||0).toLocaleString()} دج</td><td className="p-4"><select value={o.status||o.order?.status||'جديد'} onChange={e=>setOrderStatus(o.id,e.target.value)} className="px-2 py-2 rounded-xl border"><option>{statuses[0]}</option><option>{statuses[1]}</option><option>{statuses[2]}</option><option>{statuses[3]}</option><option>{statuses[4]}</option></select></td></tr>)}</tbody></table></div></section>}
      {tab==='subscriptions'&&<section className="bg-white rounded-3xl border border-slate-200 overflow-hidden"><div className="p-5 border-b"><h2 className="font-black">إدارة اشتراكات البائعين</h2><p className="text-xs text-slate-500 mt-1">اشتراك البائع فقط — بدون عمولات أو طلبات سحب أرباح.</p></div><div className="grid md:grid-cols-2 gap-4 p-5">{adminStores.map(s=><div key={s.id} className="border rounded-2xl p-4"><div className="flex justify-between"><div><b>{s.name}</b><p className="text-xs text-slate-500">{s.merchantName}</p></div><span className="text-[10px] px-2 py-1 bg-indigo-50 text-indigo-700 rounded-lg font-bold">{s.subscription?.status||'غير محدد'}</span></div><div className="grid grid-cols-2 gap-2 mt-4">{(['active_trial','subscribed','pending_baridimob','expired'] as const).map(st=><button key={st} onClick={()=>setSubscription(s,st)} className="py-2 rounded-xl bg-slate-50 border text-[10px] font-bold hover:bg-indigo-50">{st==='active_trial'?'تجربة 30 يوم':st==='subscribed'?'مفعل':'معلق / منتهٍ'}</button>)}</div></div>)}</div></section>}
    </main>
    {editingProduct&&<div className="fixed inset-0 z-50 bg-slate-950/50 flex items-center justify-center p-4"><div className="bg-white rounded-3xl w-full max-w-lg p-5 space-y-4"><div className="flex justify-between items-center"><h3 className="font-black">تعديل المنتج</h3><button onClick={()=>setEditingProduct(null)}><X/></button></div><input value={editingProduct.product.title} onChange={e=>setEditingProduct(x=>x&&({...x,product:{...x.product,title:e.target.value}}))} className="w-full border rounded-xl p-3" placeholder="اسم المنتج"/><div className="grid grid-cols-2 gap-3"><input type="number" value={editingProduct.product.price} onChange={e=>setEditingProduct(x=>x&&({...x,product:{...x.product,price:Number(e.target.value)}}))} className="border rounded-xl p-3" placeholder="السعر"/><input type="number" value={editingProduct.product.stock} onChange={e=>setEditingProduct(x=>x&&({...x,product:{...x.product,stock:Number(e.target.value)}}))} className="border rounded-xl p-3" placeholder="المخزون"/></div><div className="flex gap-2"><button onClick={()=>setEditingProduct(null)} className="flex-1 py-3 rounded-xl bg-slate-100 font-bold">إلغاء</button><button onClick={saveProduct} className="flex-1 py-3 rounded-xl bg-indigo-600 text-white font-bold flex items-center justify-center gap-2"><Save className="w-4 h-4"/>حفظ</button></div></div></div>}
  </div>;
};
